import { strToU8, zipSync } from 'fflate';
import type { Env } from './env';

type Quarter = { quarter:string; total:number; platform?:number; push?:number };
type SalesRow = { vdl:string; cod_del:string; delegate:string; client:string; classification:string; route:string; previous_vrn:number; current_vrn:number; variation:number; monthly_sales:string|Record<string,number>; quarters_json:string|Quarter[] };
export type OpeningPharmacy = { quarter:string; codDel:string; delegate:string; vdl:string; client:string; classification:string; saleQ:number };

const parse=<T>(value:unknown,fallback:T):T=>{if(typeof value!=='string')return (value as T)||fallback;try{return JSON.parse(value)as T}catch{return fallback}};
export function ytdStatus(previous:number,current:number){if(previous<=0&&current>0)return'Apertura';if(previous>0&&current<=0)return'Compra detenida';if(current>previous)return'Crecimiento';if(current<previous)return'Decrecimiento';return'Estable';}
const fiscalStart=(label:string)=>Number(label.match(/Q[1-4]\s*(\d{2})\s*-\s*\d{2}/i)?.[1]||0);

export function buildSalesAnalytics(rows:SalesRow[]){
  const openings:OpeningPharmacy[]=[],changes:any[]=[];
  for(const row of rows){
    const quarters=parse<Quarter[]>(row.quarters_json,[]),months=parse<Record<string,number>>(row.monthly_sales,{}),monthKeys=Object.keys(months).filter(x=>/^\d{4}-\d{2}$/.test(x)).sort(),latestMonth=monthKeys.at(-1)||'',latestMonthSale=Number(months[latestMonth]||0),previous=Number(row.previous_vrn||0),current=Number(row.current_vrn||0);
    const baselineSales=quarters.filter(q=>fiscalStart(q.quarter)===24).reduce((sum,q)=>sum+Number(q.total||0),0);
    if(baselineSales<=0){const candidates=quarters.filter(q=>fiscalStart(q.quarter)>=25);const first=candidates.find(q=>Number(q.total||0)>0);if(first)openings.push({quarter:first.quarter,codDel:row.cod_del,delegate:row.delegate,vdl:row.vdl,client:row.client,classification:row.classification,saleQ:Number(first.total||0)});}
    changes.push({vdl:row.vdl,cod_del:row.cod_del,delegate:row.delegate,client:row.client,classification:row.classification,route:row.route,previous_vrn:previous,current_vrn:current,variation:current-previous,ytd_status:ytdStatus(previous,current),latest_month:latestMonth,latest_month_sale:latestMonthSale,ordered_this_month:latestMonthSale>0,gap_to_equal_ytd:latestMonthSale>0?Math.max(0,previous-current):null});
  }
  const quarterLabels=[...new Set(rows.flatMap(row=>parse<Quarter[]>(row.quarters_json,[]).filter(q=>fiscalStart(q.quarter)>=25).map(q=>q.quarter)))];
  const openingsByQuarter=quarterLabels.map(quarter=>{const pharmacies=openings.filter(x=>x.quarter===quarter),delegateMap=new Map<string,{codDel:string;delegate:string;count:number;sales:number;pharmacies:OpeningPharmacy[]}>();for(const item of pharmacies){let group=delegateMap.get(item.codDel);if(!group){group={codDel:item.codDel,delegate:item.delegate,count:0,sales:0,pharmacies:[]};delegateMap.set(item.codDel,group)}group.count++;group.sales+=item.saleQ;group.pharmacies.push(item)}return{quarter,count:pharmacies.length,sales:pharmacies.reduce((n,x)=>n+x.saleQ,0),delegates:[...delegateMap.values()].sort((a,b)=>b.count-a.count||b.sales-a.sales),pharmacies:pharmacies.sort((a,b)=>b.saleQ-a.saleQ)};});
  return{openingsByQuarter,changes:changes.sort((a,b)=>Math.abs(b.variation)-Math.abs(a.variation)),latestMonth:changes.map(x=>x.latest_month).sort().at(-1)||''};
}

const xml=(value:unknown)=>String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
const letters=(n:number)=>{let out='';while(n){n--;out=String.fromCharCode(65+n%26)+out;n=Math.floor(n/26)}return out};
function sheetXml(rows:(string|number)[][],currencyColumns:number[]){const body=rows.map((row,r)=>'<row r="'+(r+1)+'">'+row.map((value,c)=>{const ref=letters(c+1)+(r+1),style=r===0?'1':currencyColumns.includes(c)?'2':'0';return typeof value==='number'?'<c r="'+ref+'" s="'+style+'"><v>'+value+'</v></c>':'<c r="'+ref+'" s="'+style+'" t="inlineStr"><is><t xml:space="preserve">'+xml(value)+'</t></is></c>'}).join('')+'</row>').join(''),last=letters(Math.max(1,rows[0]?.length||1))+Math.max(1,rows.length);return'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><sheetViews><sheetView workbookViewId="0"><pane ySplit="1" topLeftCell="A2" activePane="bottomLeft" state="frozen"/></sheetView></sheetViews><cols><col min="1" max="1" width="20" customWidth="1"/><col min="2" max="2" width="18" customWidth="1"/><col min="3" max="3" width="14" customWidth="1"/><col min="4" max="8" width="28" customWidth="1"/></cols><sheetData>'+body+'</sheetData><autoFilter ref="A1:'+last+'"/></worksheet>';}
export function openingsWorkbook(openingsByQuarter:ReturnType<typeof buildSalesAnalytics>['openingsByQuarter']){
  const summary:(string|number)[][]=[['Ámbito','Trimestre','Aperturas','Venta Q']];const detail:(string|number)[][]=[['Trimestre','Delegado','VDL','Farmacia','Clasificación','Venta Q']];
  for(const q of openingsByQuarter){summary.push(['Total área',q.quarter,q.count,q.sales]);for(const d of q.delegates)summary.push([d.delegate,q.quarter,d.count,d.sales]);for(const p of q.pharmacies)detail.push([p.quarter,p.delegate,p.vdl,p.client,p.classification,p.saleQ]);}
  const files:Record<string,Uint8Array>={
    '[Content_Types].xml':strToU8('<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/></Types>'),
    '_rels/.rels':strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>'),
    'xl/workbook.xml':strToU8('<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets><sheet name="Resumen por Q" sheetId="1" r:id="rId1"/><sheet name="Farmacias abiertas" sheetId="2" r:id="rId2"/></sheets></workbook>'),
    'xl/_rels/workbook.xml.rels':strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles" Target="styles.xml"/></Relationships>'),
    'xl/styles.xml':strToU8('<?xml version="1.0" encoding="UTF-8"?><styleSheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><numFmts count="1"><numFmt numFmtId="164" formatCode="#,##0.00 [$€-es-ES]"/></numFmts><fonts count="2"><font><sz val="11"/><name val="Aptos"/></font><font><b/><color rgb="FFFFFFFF"/><sz val="11"/><name val="Aptos"/></font></fonts><fills count="3"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill><fill><patternFill patternType="solid"><fgColor rgb="FF4F46E5"/><bgColor indexed="64"/></patternFill></fill></fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="3"><xf numFmtId="0" fontId="0" fillId="0" borderId="0" xfId="0"/><xf numFmtId="0" fontId="1" fillId="2" borderId="0" xfId="0" applyFill="1" applyFont="1"/><xf numFmtId="164" fontId="0" fillId="0" borderId="0" xfId="0" applyNumberFormat="1"/></cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>'),
    'xl/worksheets/sheet1.xml':strToU8(sheetXml(summary,[3])),
    'xl/worksheets/sheet2.xml':strToU8(sheetXml(detail,[5])),
  };return zipSync(files,{level:6});
}

async function analyticsData(env:Env,url:URL){const imports=(await env.DB.prepare('SELECT id,source_date FROM sales_dashboard_imports ORDER BY source_date DESC,imported_at DESC LIMIT 16').all<any>()).results,selectedId=url.searchParams.get('import')||imports[0]?.id,id=imports.find(x=>x.id===selectedId)?.id||imports[0]?.id;if(!id)return{ok:true,empty:true,openingsByQuarter:[],changes:[],latestMonth:''};const rows=(await env.DB.prepare('SELECT c.vdl,c.cod_del,c.delegate,c.client,c.classification,c.route,c.previous_vrn,c.current_vrn,c.variation,d.monthly_sales,d.quarters_json FROM sales_dashboard_clients c JOIN sales_dashboard_client_details d ON d.import_id=c.import_id AND d.vdl=c.vdl WHERE c.import_id=?').bind(id).all<SalesRow>()).results,all=buildSalesAnalytics(rows),delegate=url.searchParams.get('delegate')||'';return{ok:true,empty:false,selectedDelegate:delegate,openingsByQuarter:all.openingsByQuarter,changes:delegate?all.changes.filter(x=>x.cod_del===delegate):all.changes,latestMonth:all.latestMonth};}
export async function salesAnalyticsApi(req:Request,env:Env){const url=new URL(req.url);if(req.method!=='GET')return Response.json({error:'Método no permitido'},{status:405});try{const data=await analyticsData(env,url);if(url.pathname.endsWith('.xlsx')){if(data.empty)return new Response('Sin datos',{status:404});const bytes=openingsWorkbook(data.openingsByQuarter);return new Response(bytes,{headers:{'content-type':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet','content-disposition':'attachment; filename="aperturas-por-trimestre.xlsx"','cache-control':'no-store'}});}return Response.json(data,{headers:{'cache-control':'no-store'}});}catch(error){return Response.json({error:error instanceof Error?error.message:'No se pudo calcular el análisis comercial'},{status:400});}}
