export const SALES_UI_JS = String.raw`
let salesClientOptions=[];
function salesSearchKey(value){return String(value||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLocaleLowerCase('es').replace(/\s+/g,' ').trim()}
function visualChart(rows,label,value,format=money,forced){
  const type=forced||$('#sales-chart').value,items=rows.map(x=>({label:String(label(x)),value:Number(value(x)||0)}));
  if(!items.length)return'<p class="muted">Sin datos.</p>';
  if(type==='bar')return bars(rows,label,value,format);
  if(type==='donut'){const total=items.reduce((n,x)=>n+Math.max(0,x.value),0)||1,c=2*Math.PI*72;let offset=0;const circles=items.map((x,i)=>{const part=Math.max(0,x.value)/total*c,tag='<circle cx="110" cy="110" r="72" fill="none" stroke="'+chartColors[i%chartColors.length]+'" stroke-width="34" stroke-dasharray="'+part+' '+(c-part)+'" stroke-dashoffset="'+(-offset)+'" transform="rotate(-90 110 110)"/>';offset+=part;return tag}).join('');return'<div class="donut-layout"><svg class="chart-svg" viewBox="0 0 220 220" role="img">'+circles+'<text x="110" y="107" fill="currentColor" text-anchor="middle" font-size="14">Total</text><text x="110" y="130" fill="currentColor" text-anchor="middle" font-size="20">'+format(total)+'</text></svg><div class="chart-legend">'+items.map((x,i)=>'<span><i class="legend-dot" style="background:'+chartColors[i%chartColors.length]+'"></i>'+esc(x.label)+' · '+format(x.value)+'</span>').join('')+'</div></div>'}
  const max=Math.max(...items.map(x=>x.value),1),min=Math.min(...items.map(x=>x.value),0),span=max-min||1,points=items.map((x,i)=>({x:items.length===1?320:48+i*(544/(items.length-1)),y:176-(x.value-min)/span*124,...x})),line=points.map(p=>p.x+','+p.y).join(' '),area='48,176 '+line+' 592,176';
  return'<svg class="chart-svg quarter-line-chart" viewBox="0 0 640 230" role="img" aria-label="Evolución por trimestres"><defs><linearGradient id="aravitas-line-area" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stop-color="#5DD3F0" stop-opacity=".34"/><stop offset="100%" stop-color="#5DD3F0" stop-opacity="0"/></linearGradient></defs><line x1="48" y1="52" x2="592" y2="52" stroke="#2A3150" stroke-dasharray="4 5"/><line x1="48" y1="114" x2="592" y2="114" stroke="#2A3150" stroke-dasharray="4 5"/><line x1="48" y1="176" x2="592" y2="176" stroke="#2A3150"/><polygon points="'+area+'" fill="url(#aravitas-line-area)"/><polyline points="'+line+'" fill="none" stroke="#5DD3F0" stroke-width="4" stroke-linecap="round" stroke-linejoin="round"/>'+points.map((p,i)=>'<circle cx="'+p.x+'" cy="'+p.y+'" r="6" fill="#171c31" stroke="'+chartColors[i%chartColors.length]+'" stroke-width="4"/><text x="'+p.x+'" y="'+Math.max(20,p.y-14)+'" fill="currentColor" text-anchor="middle" font-size="11" font-weight="600">'+esc(format(p.value))+'</text><text x="'+p.x+'" y="207" fill="#9AA3BF" text-anchor="middle" font-size="11">'+esc(p.label.slice(0,16))+'</text>').join('')+'</svg>'
}
function enhanceSalesDashboardFilters(){
  const select=$('#sales-client');
  if(!select||$('#sales-client-search'))return;
  select.hidden=true;
  const search=document.createElement('input');
  search.id='sales-client-search';search.type='search';search.autocomplete='off';search.placeholder='Escribe farmacia, VDL, clasificación o delegado…';
  search.setAttribute('aria-label','Buscar farmacia');search.setAttribute('aria-controls','sales-client-results');search.setAttribute('aria-expanded','false');
  search.oninput=showSalesClientMatches;search.onfocus=showSalesClientMatches;search.onkeydown=salesClientKeydown;search.onblur=()=>setTimeout(closeSalesClientMatches,180);
  const results=document.createElement('div');results.id='sales-client-results';results.className='client-search-results';results.hidden=true;results.setAttribute('role','listbox');
  select.insertAdjacentElement('afterend',search);search.insertAdjacentElement('afterend',results);
  const chart=$('#sales-chart');
  if(chart){chart.replaceChildren(new Option('Líneas · evolución','line'),new Option('Barras · comparación','bar'),new Option('Sectores · distribución','donut'));chart.value=localStorage.getItem('aravitas-sales-chart')||'line';chart.addEventListener('change',()=>localStorage.setItem('aravitas-sales-chart',chart.value));}
  const quarter=$('#sales-quarter');if(quarter)quarter.addEventListener('change',()=>setTimeout(()=>renderSalesExtensions(lastSalesData),0));
  if(chart&&!$('#sales-ytd-status')){const label=document.createElement('label');label.textContent='Tendencia YTD';const status=document.createElement('select');status.id='sales-ytd-status';status.append(new Option('Todas',''),new Option('Crecimiento','Crecimiento'),new Option('Decrecimiento','Decrecimiento'),new Option('Apertura','Apertura'),new Option('Compra detenida','Compra detenida'),new Option('Estable','Estable'));status.onchange=()=>renderSalesExtensions(lastSalesData);label.append(status);chart.closest('label')?.insertAdjacentElement('afterend',label)}
  const controls=document.querySelector('.product-filters'),pdf=controls?.querySelector('button.primary');if(controls&&pdf&&!$('#sales-openings-download')){const download=document.createElement('button');download.id='sales-openings-download';download.className='btn';download.type='button';download.textContent='Descargar aperturas Excel';download.onclick=downloadOpeningsExcel;controls.insertBefore(download,pdf)}
  document.head.insertAdjacentHTML('beforeend','<style>.client-search-results{position:absolute;z-index:60;left:0;right:0;top:100%;max-height:320px;overflow:auto;margin-top:5px;padding:6px;border:1px solid var(--line);border-radius:12px;background:#171c31;box-shadow:0 18px 45px rgba(0,0,0,.4)}.client-search-results button{display:grid;width:100%;gap:2px;padding:10px 11px;border:0;border-radius:8px;background:transparent;color:var(--text);text-align:left;cursor:pointer}.client-search-results button:hover,.client-search-results button:focus{background:var(--surface);outline:none}.client-search-results small{color:var(--muted)}#sales-client-search{padding-right:38px}label:has(>#sales-client){position:relative}.sales-search-empty{padding:12px;color:var(--muted);font-size:13px}.sales-openings h4{margin:22px 0 8px}.sales-openings .section-head{align-items:flex-start}.sales-openings table{min-width:620px}</style>');
}
function matchingSalesClients(query){const terms=salesSearchKey(query).split(' ').filter(Boolean);if(!terms.length)return[];return salesClientOptions.filter(item=>{const haystack=salesSearchKey([item.client,item.vdl,item.classification,item.delegate].join(' '));return terms.every(term=>haystack.includes(term))}).slice(0,18)}
function showSalesClientMatches(){const input=$('#sales-client-search'),host=$('#sales-client-results');if(!input||!host)return;const matches=matchingSalesClients(input.value);host.replaceChildren();if(!input.value.trim()){host.hidden=true;input.setAttribute('aria-expanded','false');return}if(!matches.length){const empty=document.createElement('div');empty.className='sales-search-empty';empty.textContent='No hay coincidencias con estos criterios.';host.append(empty)}else matches.forEach(item=>{const button=document.createElement('button');button.type='button';button.setAttribute('role','option');const name=document.createElement('b');name.textContent=item.client;const detail=document.createElement('small');detail.textContent=[item.classification,'VDL '+item.vdl,delegateName(item.delegate)].filter(Boolean).join(' · ');button.append(name,detail);button.onmousedown=event=>event.preventDefault();button.onclick=()=>selectSalesClient(item);host.append(button)});host.hidden=false;input.setAttribute('aria-expanded','true')}
function closeSalesClientMatches(){const host=$('#sales-client-results'),input=$('#sales-client-search');if(host)host.hidden=true;if(input)input.setAttribute('aria-expanded','false')}
function salesClientKeydown(event){if(event.key!=='Enter')return;event.preventDefault();const matches=matchingSalesClients(event.currentTarget.value);if(matches.length)selectSalesClient(matches[0]);else $('#sales-status').textContent='No encuentro una farmacia que coincida. Prueba con parte del nombre, el VDL, la clasificación o el delegado.'}
function selectSalesClient(item){$('#sales-client').value=item.vdl;$('#sales-client-search').value=item.client;closeSalesClientMatches();loadSalesDashboard()}
function resolveSalesClientSearch(){const input=$('#sales-client-search'),select=$('#sales-client');if(!input||!select||select.value||!input.value.trim())return true;const key=salesSearchKey(input.value),exact=salesClientOptions.find(item=>salesSearchKey(item.client)===key);if(exact){select.value=exact.vdl;input.value=exact.client;return true}const matches=salesClientOptions.filter(item=>salesSearchKey([item.client,item.vdl,item.classification,item.delegate].join(' ')).includes(key));if(matches.length===1){select.value=matches[0].vdl;input.value=matches[0].client;return true}showSalesClientMatches();$('#sales-status').textContent=matches.length?'Selecciona una de las farmacias coincidentes.':'No encuentro una farmacia con ese criterio.';return false}
function syncSalesFilters(j){
  enhanceSalesDashboardFilters();
  fillSelect($('#sales-snapshot'),j.imports,x=>x.id,x=>x.source_date+' · '+x.source_name,'Último disponible');$('#sales-snapshot').value=j.latest.id;
  fillSelect($('#sales-delegate'),j.delegates,x=>x.cod_del,x=>delegateName(x.delegate),'Todo el equipo');$('#sales-delegate').value=j.selectedDelegate;
  salesClientOptions=(j.clientOptions||[]).map(item=>({...item,delegate:(j.delegates.find(d=>d.cod_del===item.cod_del)||{}).delegate||''}));
  fillSelect($('#sales-client'),salesClientOptions,x=>x.vdl,x=>x.client+' · '+x.classification,'Todas las farmacias');$('#sales-client').value=j.selectedClient;
  const selected=salesClientOptions.find(x=>x.vdl===j.selectedClient),search=$('#sales-client-search');if(search)search.value=selected?selected.client:'';
  const list=$('#molecule-list');list.replaceChildren(...j.molecules.map(x=>Object.assign(document.createElement('option'),{value:x})));
  const q=new Map();for(const d of j.delegateDetails)for(const point of d.quarters)q.set(point.quarter,point.quarter);fillSelect($('#sales-quarter'),[...q.values()],x=>x,x=>x,'Último disponible');
}
function salesDelegateChanged(){$('#sales-client').value='';const search=$('#sales-client-search');if(search)search.value='';closeSalesClientMatches();loadSalesDashboard()}
function clearSalesFilters(){$('#sales-delegate').value='';$('#sales-client').value='';const search=$('#sales-client-search');if(search)search.value='';$('#sales-quarter').value='';$('#sales-molecule').value='';$('#sales-product-search').value='';closeSalesClientMatches();loadSalesDashboard()}
function statusClass(s){return/^crecimiento/i.test(String(s||''))?'growth':/apertura/i.test(String(s||''))?'opening':/detenida/i.test(String(s||''))?'stopped':/^decrecimiento/i.test(String(s||''))?'decline':''}
function ytdStatusLabel(previous,current){previous=Number(previous||0);current=Number(current||0);if(previous<=0&&current>0)return'Apertura';if(previous>0&&current<=0)return'Compra detenida';if(current>previous)return'Crecimiento';if(current<previous)return'Decrecimiento';return'Estable'}
function monthName(value){if(!value)return'último mes';const [year,month]=value.split('-'),names=['ene','feb','mar','abr','may','jun','jul','ago','sep','oct','nov','dic'];return(names[Number(month)-1]||month)+' '+year}
function downloadOpeningsExcel(){const p=salesParams();p.delete('delegate');p.delete('client');p.delete('molecule');p.delete('product');window.open('/api/sales-dashboard/openings.xlsx?'+p.toString(),'_blank','noopener')}
function renderSalesExtensions(j){
  if(!j)return;const openingsByQuarter=j.openingsByQuarter||[];
  const selectedQuarter=$('#sales-quarter').value||openingsByQuarter.at(-1)?.quarter||'',quarter=openingsByQuarter.find(x=>x.quarter===selectedQuarter)||openingsByQuarter.at(-1),delegate=$('#sales-delegate').value||'',delegateGroup=quarter?.delegates.find(x=>x.codDel===delegate),count=delegate?Number(delegateGroup?.count||0):Number(quarter?.count||0),sales=delegate?Number(delegateGroup?.sales||0):Number(quarter?.sales||0);
  const openingMetric=[...document.querySelectorAll('#sales-dashboard .metric')].find(x=>x.querySelector('small')?.textContent?.startsWith('Aperturas'));
  if(openingMetric){openingMetric.querySelector('small').textContent='Aperturas '+selectedQuarter;openingMetric.querySelector('strong').textContent=count.toLocaleString('es-ES');openingMetric.querySelectorAll('small')[1].textContent=money(sales)+' de venta Q · cada farmacia se cuenta una sola vez'}
  const blocks=[...document.querySelectorAll('#sales-dashboard .dashboard-block')],ytdBlock=blocks.find(x=>x.querySelector('h3')?.textContent==='Crecimiento y decrecimiento YTD');
  const profilePattern=blocks.find(x=>x.querySelector('.eyebrow')?.textContent==='Ficha 360º de farmacia')?.querySelectorAll('.profile-item');if(profilePattern)for(const item of profilePattern){if(item.querySelector('small')?.textContent==='Patrón de compra'){const label=ytdStatusLabel(j.clientDetail?.previous_vrn,j.clientDetail?.current_vrn),badge=item.querySelector('b');badge.textContent=label;badge.className='trend-badge '+statusClass(label)}}
  const patternBlock=blocks.find(x=>x.querySelector('h3')?.textContent==='Patrones de compra');if(patternBlock){const counts={};for(const row of j.changes)counts[row.ytd_status]=(counts[row.ytd_status]||0)+1;const patterns=Object.entries(counts).map(([pattern,count])=>({pattern,count}));patternBlock.innerHTML='<h3>Tendencia YTD de farmacias</h3>'+visualChart(patterns,x=>x.pattern,x=>x.count,n=>Number(n).toLocaleString('es-ES'),'donut')}
  const statusFilter=$('#sales-ytd-status')?.value||'',filteredChanges=statusFilter?j.changes.filter(x=>x.ytd_status===statusFilter):j.changes;
  if(ytdBlock)ytdBlock.innerHTML='<h3>Crecimiento y decrecimiento YTD</h3><p class="muted small">'+(statusFilter?'Mostrando '+esc(statusFilter.toLowerCase())+'. ':'')+'La tendencia compara exclusivamente YTD 26-27 frente a YTD 25-26. El pedido mensual permite distinguir una caída real de una compra todavía pendiente.</p>'+rowsTable(['Farmacia','Delegado','Clasificación','YTD 25-26','YTD 26-27','Variación','Tendencia YTD','Venta '+monthName(j.latestMonth),'Pedido del mes','Falta para igualar YTD','Ruta'],filteredChanges,x=>[esc(x.client),esc(delegateName(x.delegate)),esc(x.classification),money(x.previous_vrn),money(x.current_vrn),'<span class="'+(Number(x.variation)>=0?'ok':'bad')+'">'+money(x.variation)+'</span>','<span class="trend-badge '+statusClass(x.ytd_status)+'">'+esc(x.ytd_status)+'</span>',money(x.latest_month_sale),x.ordered_this_month?'<span class="ok">Realizado</span>':'<span class="warn">Pendiente</span>',x.ordered_this_month?money(x.gap_to_equal_ytd):'<span class="muted">Pendiente de pedido</span>',esc(x.route||'—')]);
  document.querySelector('#sales-openings')?.remove();if(!quarter)return;
  const detail=delegate?quarter.pharmacies.filter(x=>x.codDel===delegate):quarter.pharmacies,section=document.createElement('section');section.id='sales-openings';section.className='dashboard-block wide sales-openings';section.innerHTML='<div class="section-head"><div><h3>Aperturas por trimestre</h3><p class="muted small">Primera compra positiva tras no comprar en el periodo base 24-25. La farmacia queda asignada únicamente al trimestre en el que abre.</p></div><button class="btn primary" type="button" onclick="downloadOpeningsExcel()">Descargar aperturas Excel</button></div><h4>Resumen del área</h4>'+rowsTable(['Trimestre','Aperturas','Venta Q'],openingsByQuarter,x=>[esc(x.quarter),Number(x.count).toLocaleString('es-ES'),money(x.sales)])+'<h4>'+esc(selectedQuarter)+' · por delegado</h4>'+rowsTable(['Delegado','Aperturas','Venta Q'],quarter.delegates,x=>[esc(delegateName(x.delegate)),Number(x.count).toLocaleString('es-ES'),money(x.sales)])+'<h4>Farmacias abiertas'+(delegate?' · '+esc(delegateName(delegateGroup?.delegate||delegate)):'')+'</h4>'+rowsTable(['Farmacia','Delegado','VDL','Clasificación','Venta Q'],detail,x=>[esc(x.client),esc(delegateName(x.delegate)),esc(x.vdl),esc(x.classification),money(x.saleQ)]);
  if(ytdBlock)ytdBlock.insertAdjacentElement('beforebegin',section);else $('#sales-dashboard').append(section)
}
async function loadSalesDashboard(reset=false){if(!$('#sales-delegate'))return;if(reset){$('#sales-snapshot').value='';$('#sales-delegate').value='';$('#sales-client').value='';const search=$('#sales-client-search');if(search)search.value=''}else if(!resolveSalesClientSearch())return;$('#sales-status').textContent='Calculando indicadores, aperturas y patrones comerciales…';try{const params=salesParams(),mainResponse=await fetch('/api/sales-dashboard?'+params),j=await mainResponse.json();if(!mainResponse.ok)throw new Error(j.error);if(j.empty){$('#sales-status').textContent='Sube el Excel semanal o envíalo a Aravitas por Telegram para crear el primer cuadro de mando.';$('#sales-dashboard').replaceChildren();return}let analytics={};try{const response=await fetch('/api/sales-dashboard/analytics?'+params);if(response.ok)analytics=await response.json()}catch{}Object.assign(j,analytics);if(!j.changes?.some(x=>x.ytd_status))j.changes=(j.changes||[]).map(x=>({...x,ytd_status:ytdStatusLabel(x.previous_vrn,x.current_vrn),latest_month:'',latest_month_sale:0,ordered_this_month:false,gap_to_equal_ytd:null}));syncSalesFilters(j);lastSalesData=j;renderSalesDashboard(j);renderSalesExtensions(j);$('#sales-status').textContent='Datos del '+j.latest.source_date+' · '+j.latest.client_count+' farmacias · '+j.latest.product_count+' presentaciones · origen '+j.latest.source_channel;}catch(e){$('#sales-status').textContent=e.message}}
enhanceSalesDashboardFilters();
`;
