import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Script } from 'node:vm';
import ts from 'typescript';
const source=readFileSync(new URL('../src/dashboard.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ES2022}}).outputText.replace(/^import .*;$/gm,'').replace(/export /g,'');
const {page,appShell}=new Function(js+';return {page,appShell}')();
test('programming controls only appear for administrator',()=>{
 assert.ok(appShell('info@apdsport.com').includes('id="programming"'));
 assert.ok(!appShell('aradelg@gmail.com').includes('id="programming"'));
});
test('generated browser JavaScript parses and exposes Aravitas sales dashboard',async()=>{
 const html=await page({BRAND_NAME:'Aravitas'},appShell('info@apdsport.com')).text();
 const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
 assert.doesNotThrow(()=>new Script(script));
 assert.ok(html.includes('Redactor de correo'));
 assert.ok(html.includes('Cuadro de mando'));
 assert.ok(html.includes('GERENTE DE ALTO IMPACTO'));
 assert.ok(html.includes('sales-client'));
 assert.ok(html.includes('sales-quarter'));
 assert.ok(html.includes('sales-chart'));
 assert.ok(html.includes('Descargar informe PDF'));
 assert.ok(!html.includes('Oportunidades de activación'));
 assert.ok(!html.includes('Productos foco'));
 assert.ok(html.includes('Aravitas'));
 assert.ok(!html.includes('Nuvia'));
 assert.ok(html.includes('draft-file'));
 assert.ok(html.includes('draft-clarification'));
 assert.ok(html.includes('Guardar correo completo en Gmail'));
 assert.ok(html.includes('knowledge-text'));
 assert.ok(!html.includes('Transcribir audio'));
});
