import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Script } from 'node:vm';
import ts from 'typescript';
const source=readFileSync(new URL('../src/dashboard.ts',import.meta.url),'utf8');
const planningSource=readFileSync(new URL('../src/planningUi.ts',import.meta.url),'utf8');
const compilerOptions={module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022};
const planningJs=ts.transpileModule(planningSource,{compilerOptions}).outputText.replace(/export /g,'');
const salesUiSource=readFileSync(new URL('../src/salesUi.ts',import.meta.url),'utf8');
const salesUiJs=ts.transpileModule(salesUiSource,{compilerOptions}).outputText.replace(/export /g,'');
const crmUiSource=readFileSync(new URL('../src/crmUi.ts',import.meta.url),'utf8');
const crmUiJs=ts.transpileModule(crmUiSource,{compilerOptions}).outputText.replace(/export /g,'');
const js=planningJs+'\n'+salesUiJs+'\n'+crmUiJs+'\n'+ts.transpileModule(source,{compilerOptions}).outputText.replace(/^import .*;$/gm,'').replace(/export /g,'');
const {page,appShell}=new Function(js+';return {page,appShell}')();
test('programming controls only appear for administrator',()=>{
 assert.ok(appShell('info@apdsport.com').includes('id="programming"'));
 assert.ok(!appShell('aradelg@gmail.com').includes('id="programming"'));
});
test('generated browser JavaScript parses and exposes Aravitas sales dashboard',async()=>{
 const html=await page({BRAND_NAME:'Aravitas'},appShell('info@apdsport.com')).text();
 const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
 assert.doesNotThrow(()=>new Script(script));
 assert.ok(html.includes('Redactor de correo'));
 assert.ok(html.includes('Cuadro de mando'));
 assert.ok(html.includes('GERENTE DE ALTO IMPACTO'));
 assert.ok(html.includes('sales-client'));
 assert.ok(html.includes('sales-quarter'));
 assert.ok(html.includes('sales-chart'));
 assert.ok(html.includes('Descargar informe PDF'));
 assert.ok(!html.includes('Oportunidades de activación'));
 assert.ok(!html.includes('Productos foco'));
 assert.ok(html.includes('Aravitas'));
 assert.ok(!html.includes('Nuvia'));
 assert.ok(html.includes('draft-file'));
 assert.ok(html.includes('draft-clarification'));
 assert.ok(html.includes('Guardar correo completo en Gmail'));
 assert.ok(html.includes('knowledge-text'));
 assert.ok(!html.includes('Transcribir audio'));
 assert.ok(html.includes('Planificación mensual inteligente'));
 assert.ok(html.includes('planning-file'));
 assert.ok(html.includes('Previsualización editable'));
 assert.ok(html.includes('Aprobar y crear eventos'));
 assert.ok(script.includes('dropPlanningVisit'));
 assert.ok(script.includes('dirección, clasificación y ruta'));
 assert.ok(script.includes('sales-client-search'));
 assert.ok(script.includes("localStorage.getItem('aravitas-sales-chart')||'line'"));
 assert.ok(script.includes('VDL, clasificación o delegado'));
 assert.ok(script.includes('Aperturas por trimestre y delegado'));
 assert.ok(script.includes('Fuente oficial: cuadro de aperturas'));
 assert.ok(!script.includes('Farmacias abiertas'));
 assert.ok(script.includes('Falta para igualar YTD'));
 assert.ok(script.includes('monthName(j.latestMonth)'));
 assert.ok(script.includes("/decrecimiento|descenso/i"));
 assert.ok(script.includes('sales-ytd-status'));
 assert.ok(html.includes('Molécula o presentación'));
 assert.ok(html.includes('sales-product-evolution'));
 assert.ok(html.includes('sales-product-inactive'));
 assert.ok(html.includes('sales-product-sort'));
 assert.ok(html.includes('product-list'));
 assert.ok(html.includes('Molécula perdida'));
 assert.ok(html.includes('Aumento de compra'));
 assert.ok(script.includes('Molécula recuperada'));
 assert.ok(script.includes('monthsWithoutPurchase'));
 assert.ok(!html.includes('Promedio anterior'));
 assert.ok(script.includes('Buscar Brand'));
 assert.ok(script.includes('Buscar molécula, presentación o código'));
 assert.ok(script.includes('product-inline-filters'));
 assert.ok(script.includes('openMoleculeTrend'));
 assert.ok(script.includes('molecule-detail'));
 assert.ok(script.includes("Number(n).toLocaleString('es-ES')+' uds','line'"));
 assert.ok(script.includes('moleculeTable(productMonths,moleculeRows)'));
 assert.ok(!script.includes('moleculeRows.slice(0,300)'));
 assert.ok(script.includes('No hay Brands que coincidan con estos filtros'));
 assert.ok(!script.includes('Tendencia último mes'));
 assert.ok(!script.includes('Tendencia 3 meses'));
 assert.ok(script.includes('Total periodo'));
 assert.ok(script.includes('Unidades · mayor a menor'));
 assert.ok(script.includes('Todas las moléculas y presentaciones'));
 assert.ok(script.includes('Nº de clientes de más de 200 €'));
 assert.ok(script.includes('VRN plataforma'));
 assert.ok(script.includes('VRN push'));
 assert.ok(script.includes('Descargar gráfico en JPG'));
 assert.ok(script.includes('Descargar tabla JPG'));
 assert.ok(script.includes("'image/jpeg',0.94"));
 assert.ok(script.includes('installJpgTableExports'));
 assert.ok(!script.includes('↓ PNG'));
 assert.ok(script.includes('% SOW'));
 assert.ok(script.includes('% agudo'));
 assert.ok(script.includes('Dto medio'));
 assert.ok(script.includes('enableSalesLayout'));
 assert.ok(script.includes('aravitas-dashboard-layout-'));
 assert.ok(source.includes("content:'✓ Comprado · '"));
 assert.ok(script.includes('Sincronizar todo ahora'));
 assert.ok(script.includes('/api/crm/synchronize'));
 assert.ok(script.includes('Panel operativo de visitas y acompañamientos'));
 assert.ok(script.includes('Reglas que aplica Aravitas'));
 assert.ok(script.includes('Solo martes, miércoles y jueves'));
 assert.match(source,/OTC comprado[\s\S]{0,1000}\+presentationsHtml\+'<\/div>'/);
});
test('sales charts keep a high-contrast accessible visual system',()=>{
 const palette=['#22D3EE','#FACC15','#FB7185','#4ADE80','#C084FC','#F97316','#60A5FA','#A3E635','#FDE047','#2DD4BF'];
 const luminance=hex=>{
  const rgb=hex.slice(1).match(/../g).map(value=>Number.parseInt(value,16)/255).map(value=>value<=.03928?value/12.92:((value+.055)/1.055)**2.4);
  return .2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2];
 };
 const background=luminance('#0B1020');
 for(const color of palette){
  assert.ok(salesUiSource.includes(color));
  assert.ok((luminance(color)+.05)/(background+.05)>=4.5,`${color} must contrast with the chart background`);
 }
 assert.ok(salesUiSource.includes("const SALES_CHART_DASH=['','12 7','3 6','15 5 3 5']"));
 assert.ok(salesUiSource.includes('class="line-halo"'));
 assert.ok(salesUiSource.includes('class="chart-value"'));
 assert.ok(salesUiSource.includes('Último: '));
 assert.ok(salesUiSource.includes('@media(prefers-contrast:more)'));
});
