import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { Script } from 'node:vm';
import ts from 'typescript';
const source=readFileSync(new URL('../src/dashboard.ts',import.meta.url),'utf8');
const planningSource=readFileSync(new URL('../src/planningUi.ts',import.meta.url),'utf8');
const compilerOptions={module:ts.ModuleKind.ES2022,target:ts.ScriptTarget.ES2022};
const planningJs=ts.transpileModule(planningSource,{compilerOptions}).outputText.replace(/export /g,'');
const salesUiSource=readFileSync(new URL('../src/salesUi.ts',import.meta.url),'utf8');
const salesUiJs=ts.transpileModule(salesUiSource,{compilerOptions}).outputText.replace(/export /g,'');
const crmUiSource=readFileSync(new URL('../src/crmUi.ts',import.meta.url),'utf8');
const crmUiJs=ts.transpileModule(crmUiSource,{compilerOptions}).outputText.replace(/export /g,'');
const js=planningJs+'\n'+salesUiJs+'\n'+crmUiJs+'\n'+ts.transpileModule(source,{compilerOptions}).outputText.replace(/^import .*;$/gm,'').replace(/export /g,'');
const {page,appShell}=new Function(js+';return {page,appShell}')();
test('programming controls only appear for administrator',()=>{
 assert.ok(appShell('info@apdsport.com').includes('id="programming"'));
 assert.ok(!appShell('aradelg@gmail.com').includes('id="programming"'));
});
test('generated browser JavaScript parses and exposes Aravitas sales dashboard',async()=>{
 const html=await page({BRAND_NAME:'Aravitas'},appShell('info@apdsport.com')).text();
 const script=html.match(/<script>([\s\S]*?)<\/script>/)[1];
 assert.doesNotThrow(()=>new Script(script));
 assert.ok(html.includes('Redactor de correo'));
 assert.ok(html.includes('Cuadro de mando'));
 assert.ok(html.includes('GERENTE DE ALTO IMPACTO'));
 assert.ok(html.includes('sales-client'));
 assert.ok(html.includes('sales-quarter'));
 assert.ok(html.includes('sales-chart'));
 assert.ok(html.includes('Descargar informe PDF'));
 assert.ok(!html.includes('Oportunidades de activación'));
 assert.ok(!html.includes('Productos foco'));
 assert.ok(html.includes('Aravitas'));
 assert.ok(!html.includes('Nuvia'));
 assert.ok(html.includes('draft-file'));
 assert.ok(html.includes('draft-clarification'));
 assert.ok(html.includes('Guardar correo completo en Gmail'));
 assert.ok(html.includes('knowledge-text'));
 assert.ok(!html.includes('Transcribir audio'));
 assert.ok(html.includes('Planificación mensual inteligente'));
 assert.ok(html.includes('planning-file'));
 assert.ok(html.includes('Previsualización editable'));
 assert.ok(html.includes('Aprobar y crear eventos'));
 assert.ok(script.includes('dropPlanningVisit'));
 assert.ok(script.includes('dirección, clasificación y ruta'));
 assert.ok(script.includes('sales-client-search'));
 assert.ok(script.includes("localStorage.getItem('aravitas-sales-chart')||'line'"));
 assert.ok(script.includes('VDL, clasificación o delegado'));
 assert.ok(script.includes('Descargar aperturas Excel'));
 assert.ok(script.includes('Falta para igualar YTD'));
 assert.ok(script.includes('monthName(j.latestMonth)'));
 assert.ok(script.includes("/^decrecimiento/i"));
 assert.ok(script.includes('sales-ytd-status'));
 assert.ok(script.includes('Sincronizar todo ahora'));
 assert.ok(script.includes('/api/crm/synchronize'));
 assert.ok(script.includes('Panel operativo de visitas y acompañamientos'));
 assert.ok(script.includes('Reglas que aplica Aravitas'));
 assert.ok(script.includes('Solo martes, miércoles y jueves'));
});
